CREATE TABLE users
(
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,
    created_by  BIGINT,
    modified_by BIGINT,
    username    VARCHAR(255),
    role        VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE post
(
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,
    created_by  BIGINT,
    modified_by BIGINT,
    user_id     BIGINT,
    title       VARCHAR(255),
    content     VARCHAR(255),
    status      VARCHAR(255),
    CONSTRAINT pk_post PRIMARY KEY (post_id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

CREATE TABLE comment
(
    comment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,
    created_by  BIGINT,
    modified_by BIGINT,
    post_id     BIGINT,
    user_id     BIGINT,
    content     VARCHAR(255),
    parent_id   BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (post_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

CREATE TABLE report
(
    report_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,
    created_by  BIGINT,
    modified_by BIGINT,
    user_id     BIGINT,
    target_type VARCHAR(255),
    target_id   BIGINT,
    reason      VARCHAR(255),
    CONSTRAINT pk_report PRIMARY KEY (report_id)
);

ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

CREATE TABLE likes
(
    like_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    modified_at TIMESTAMP,
    created_by  BIGINT,
    modified_by BIGINT,
    user_id     BIGINT,
    target_type VARCHAR(255),
    target_id   BIGINT,
    CONSTRAINT pk_like PRIMARY KEY (like_id)
);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKE_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);